### ISSUE TITLE
Add max-width to the page

### ISSUE THREAD

**Issue by trybick** [trybick/sick-picks-client#2]
It doesn't seem to look great in the current state where the cards go all the way horizontally. A max-width can probably be added to this element, but feel free to make other tweaks too
https://github.com/trybick/sick-picks-client/blob/master/src/App.js#L20

**Comment by benfluleck** [comment]
I can try this. @trybick

**Comment by trybick** [comment]
Sure @benfluleck

**Comment by trybick** [comment]
@benfluleck A max-width was added in this PR but if you have more additions please feel free to open a new PR
