### ISSUE TITLE
Add styling to the Card

### ISSUE THREAD

**Issue by trybick** [trybick/sick-picks-client#4]
Looking for help for general styling improvements to the Sick Picks card. Multiple ideas and PRs accepted

code lives here: https://github.com/trybick/sick-picks-client/blob/master/src/components/common/Card.js

**Comment by neetigyachahar** [comment]
I can give this a try.

**Comment by DrMyuu** [comment]
Taking a look at this as well - did you have any thoughts on the way you wanted it to look?

**Comment by DrMyuu** [comment]
Just sent through a PR with some changes
